from BAmenu import Amenu
from atmop import deposit,withdraw,balance_enq,generate_pin
from BAExcept import*
import sys,cx_Oracle
def AtmMain():
          while(True):
                    Amenu()
                    try:
                              ch=int(input("Enter your choice:"))
                              if(ch==1):
                                        try:
                                                  deposit()
                                        except DepositError:
                                                  print("="*60)
                                                  print("\tDon't try invalid amount for Deposit")
                              elif(ch==2):
                                        try:
                                                  withdraw()
                                        except WithdrawError:
                                                  print("="*60)
                                                  print("\tDon't try invalid amount for Withdraw")
                                        except InsuffFundError:
                                                  print("="*60)
                                                  print("\tYou do not have sufficient balance for Withdraw")
                                                  
                              elif(ch==3):
                                        balance_enq()
                              elif(ch==4):
                                        try:
                                                  generate_pin()
                                        except InvalidAccountError:
                                                  print("="*60)
                                                  print("Sorry You entered Invalid A/C number. Please try again")
                                        except cx_Oracle.IntegrityError:
                                                  print("="*60)
                                                  print("This ATM pin generated by a person.You try another pin")
                                        
                              elif(ch==5):
                                        print("="*60)
                                        print("\tThanks for using ATM machine")
                                        print("="*60)
                                        sys.exit()
                              else:
                                        print("="*60)
                                        print("\tSorry your choice is wrong please try again")
                    except ValueError:
                              print("="*60)
                              print("\tDon't enter  String / Alphanumeric or Special symbol")
                                        
